{ fetchOdooAddon }:

fetchOdooAddon {
  pname = "mail-autogenerated-header";
  version = "18.0";
  owner = "OCA";
  repo = "mail";
  subdir = "mail_autogenerated_header";
  hash = "sha256-5M2Bq+Lgzvqz8EBM2QJkL7X6HhNiZthShy5fzwSZy4Q=";
}
