{ fetchOdooAddon }:

fetchOdooAddon {
  pname = "mail-autogenerated-header";
  version = "18.0";
  owner = "OCA";
  repo = "mail";
  subdir = "mail_autogenerated_header";
  hash = "sha256-A61IWN7EZ7sTeqznMCRj1ZkAqU7TUqAZ0ky0Qw65BDs=";
}
