{ fetchOdooAddon }:

fetchOdooAddon {
  pname = "mail-autogenerated-header";
  version = "18.0";
  owner = "OCA";
  repo = "mail";
  subdir = "mail_autogenerated_header";
  hash = "sha256-SpVYpzzEC8kVxFSsv13D0T980d7nGYokWz9QZLG2N6g=";
}
